apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marketing-tracking
  description: |
    Application to track campaigns
  annotations:
    github.com/project-slug: serenamarie125/catalog-spring-boot
    backstage.io/kubernetes-id: catalog-spring-boot
spec:
  type: website
  owner: marketing
  lifecycle: production
  system: corporate
